apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pi-web
namePrefix: preview-
commonLabels:
  selfhost.bry-guy.net/preview: "true"
resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/bry-guy/pi-ez-web
    newName: ghcr.io/bry-guy/pi-ez-web
    digest: sha256:ab9185a49ac1d8753b1df17a7d660b10fe91f86dfd8f256cf5ad41bfbc4bec33
