apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pi-web
namePrefix: preview-
commonLabels:
  selfhost.bry-guy.net/preview: "true"
resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/bry-guy/pi-ez-web
    newName: ghcr.io/bry-guy/pi-ez-web
    digest: sha256:1c43efc4b045f6123c7a1e23a75feb42771696c619c63e4e97fbd88ec1d80888
