apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pi-web
namePrefix: preview-
commonLabels:
  selfhost.bry-guy.net/preview: "true"
resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/bry-guy/pi-ez-web
    newName: ghcr.io/bry-guy/pi-ez-web
    digest: sha256:a12744cc19c714eeb916dfd6017ef964986bfe362056f54892a1a388166207d5
