apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pi-web
resources:
  - namespace.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/bry-guy/pi-ez-web
    newName: ghcr.io/bry-guy/pi-ez-web
    digest: sha256:d14dcd357cde86b6df9553686efa00819bf85f8b1bad1a189c4f172803ec1fb3
