apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pi-web
resources:
  - namespace.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/bry-guy/pi-ez-web
    newName: ghcr.io/bry-guy/pi-ez-web
    digest: sha256:0a83e0f752c8da272964c1e7880d3ac2adbbd549c56449ee48872ddbd68671d1
