apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pi-web
resources:
  - namespace.yaml
  - storage.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/bry-guy/pi-ez-web
    newName: ghcr.io/bry-guy/pi-ez-web
    digest: sha256:10802c213a9788710bb57b64645ccb0d2964b9f6de86ea78a302c0b779ce48fc
