apiVersion: v1
kind: Service
metadata:
  name: pi-ez-web
  labels:
    app.kubernetes.io/name: pi-ez-web
    app.kubernetes.io/part-of: selfhost
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pi-ez-web
    selfhost.bry-guy.net/preview: "false"
  ports:
    - name: http
      port: 3141
      targetPort: http
      protocol: TCP
