apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-web-state
  labels:
    app.kubernetes.io/name: pi-ez-web
    app.kubernetes.io/part-of: selfhost
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: selfhost-bulk-nfs
  volumeName: pi-web-state-nfs
  resources:
    requests:
      storage: 100Gi
